<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="0" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-09-24T12:13:58 IST" name="Suite" finished-at="2022-09-24T12:14:23 IST" duration-ms="25149">
    <groups>
    </groups>
    <test started-at="2022-09-24T12:13:58 IST" name="ChromeTest" finished-at="2022-09-24T12:14:23 IST" duration-ms="25149">
      <class name="Bank.VerifyHoldings">
        <test-method is-config="true" signature="launchBrowser(java.lang.String)[pri:0, instance:Bank.VerifyHoldings@1139b2f3]" started-at="2022-09-24T12:13:58 IST" name="launchBrowser" finished-at="2022-09-24T12:14:01 IST" duration-ms="2936" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method is-config="true" signature="createPOMObjects()[pri:0, instance:Bank.VerifyHoldings@1139b2f3]" started-at="2022-09-24T12:14:01 IST" name="createPOMObjects" finished-at="2022-09-24T12:14:01 IST" duration-ms="42" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createPOMObjects -->
        <test-method is-config="true" signature="openHomepage()[pri:0, instance:Bank.VerifyHoldings@1139b2f3]" started-at="2022-09-24T12:14:01 IST" name="openHomepage" finished-at="2022-09-24T12:14:13 IST" duration-ms="11637" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openHomepage -->
        <test-method signature="openHoldn()[pri:0, instance:Bank.VerifyHoldings@1139b2f3]" started-at="2022-09-24T12:14:13 IST" name="openHoldn" finished-at="2022-09-24T12:14:14 IST" duration-ms="1283" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [https://groww./user/order/stocks] but found [https://groww.in/user/order/stocks]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [https://groww./user/order/stocks] but found [https://groww.in/user/order/stocks]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at Bank.VerifyHoldings.openHoldn(VerifyHoldings.java:104)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openHoldn -->
        <test-method is-config="true" signature="logoutFromApplication(org.testng.ITestResult)[pri:0, instance:Bank.VerifyHoldings@1139b2f3]" started-at="2022-09-24T12:14:14 IST" name="logoutFromApplication" finished-at="2022-09-24T12:14:15 IST" duration-ms="894" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=openHoldn status=FAILURE method=VerifyHoldings.openHoldn()[pri:0, instance:Bank.VerifyHoldings@1139b2f3] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logoutFromApplication -->
        <test-method is-config="true" signature="openHomepage()[pri:0, instance:Bank.VerifyHoldings@1139b2f3]" started-at="2022-09-24T12:14:15 IST" name="openHomepage" finished-at="2022-09-24T12:14:22 IST" duration-ms="6755" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openHomepage -->
        <test-method signature="openHoldngs()[pri:0, instance:Bank.VerifyHoldings@1139b2f3]" started-at="2022-09-24T12:14:22 IST" name="openHoldngs" finished-at="2022-09-24T12:14:22 IST" duration-ms="659" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [Dashboard - Grow] but found [Dashboard - Groww]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Dashboard - Grow] but found [Dashboard - Groww]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at Bank.VerifyHoldings.openHoldngs(VerifyHoldings.java:93)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openHoldngs -->
        <test-method is-config="true" signature="logoutFromApplication(org.testng.ITestResult)[pri:0, instance:Bank.VerifyHoldings@1139b2f3]" started-at="2022-09-24T12:14:22 IST" name="logoutFromApplication" finished-at="2022-09-24T12:14:23 IST" duration-ms="467" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=openHoldngs status=FAILURE method=VerifyHoldings.openHoldngs()[pri:0, instance:Bank.VerifyHoldings@1139b2f3] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logoutFromApplication -->
        <test-method is-config="true" signature="cleanPOMObject()[pri:0, instance:Bank.VerifyHoldings@1139b2f3]" started-at="2022-09-24T12:14:23 IST" name="cleanPOMObject" finished-at="2022-09-24T12:14:23 IST" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanPOMObject -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:Bank.VerifyHoldings@1139b2f3]" started-at="2022-09-24T12:14:23 IST" name="closeBrowser" finished-at="2022-09-24T12:14:23 IST" duration-ms="409" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- Bank.VerifyHoldings -->
    </test> <!-- ChromeTest -->
  </suite> <!-- Suite -->
</testng-results>
